name = "SIGPROC"
uuid = "dc4e74f6-7eb3-495c-9715-1b3901ea274a"
authors = ["Kiran Shila <me@kiranshila.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
